# -*- coding: utf-8 -*-
"""computational_routine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Ww4QW1bvSCJ2-q1ACyNjYEwLgzibllZ
"""

#07-May-26, Noor Natour
#Import packages and functions needed for probability calculations, statistical tests, table generation, and plotting.

from itertools import combinations
from math import prod, comb
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.stats import ks_2samp, gmean
import sys
import matplotlib
import scipy

#Print Python and package versions used in the analysis.

print("Python:", sys.version)
print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
print("Matplotlib:", matplotlib.__version__)
print("SciPy:", scipy.__version__)

#Load feature probabilities and observed neuron counts from csv files.

df=pd.read_csv("observed_neurons.csv")
df_obs=pd.read_csv('observed_counts.csv')
feature_probs={row["feature"]: row["count"]/row["total"] for _, row in df.iterrows()}
n_neurons_all=df["total"].iloc[0]

#Probability calculation routine
#This function calculates:
##the probability of exactly k encoded features
##the expected number of neurons encoding k features
#assuming independent encoding between features.

def probability_k_features(k, probs_dict, n_neurons):
  features=list(probs_dict.keys())
  total_prob=0
  for active_neurons in combinations(features, k):
    p=1
    for f in features:
      if f in active_neurons:
        p*=probs_dict[f]
      else:
        p*=(1-probs_dict[f])
    total_prob+=p
  expected_neurons=n_neurons*total_prob
  return total_prob, expected_neurons

#Binomial right-tail probability
#This function calculates the right-tail probability for an observed count in a binomial distribution.

def binom_right_tail(n, k_obs, p):
    total=0.0
    for k in range(k_obs, n+1):
        pmf=comb(n, k)*(p**k)*((1-p)**(n-k))
        total+=pmf
    return total

#Discrete distribution expansion
#This function converts discrete values and their counts into an expanded vector representation.
def enumerate_discrete(values, counts):
  enumerated=[]
  for value, count in zip(values, counts):
    enumerated.extend([int(value)]*int(count))
  return enumerated