# -*- coding: utf-8 -*-
"""computational_routines.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Ww4QW1bvSCJ2-q1ACyNjYEwLgzibllZ
"""

#07-May-26, Noor Natour
#Import packages and functions needed for probability calculations, statistical tests, table generation, and plotting.

from itertools import combinations
import numpy as np
from scipy.stats import ks_2samp

#Probability calculation routine
#This function calculates:
##the probability of exactly k encoded features
##the expected number of neurons encoding k features
#assuming independent encoding between features.

def probability_k_features(k, probs_dict, n_neurons):
  features=list(probs_dict.keys())
  total_prob=0
  for active_neurons in combinations(features, k):
    p=1
    for f in features:
      if f in active_neurons:
        p*=probs_dict[f]
      else:
        p*=(1-probs_dict[f])
    total_prob+=p
  expected_neurons=n_neurons*total_prob
  return total_prob, expected_neurons

#Binomial right-tail probability
#This function calculates the right-tail probability for an observed count in a binomial distribution.

def binom_right_tail(n, k_obs, p):
    total=0.0
    for k in range(k_obs, n+1):
        pmf=comb(n, k)*(p**k)*((1-p)**(n-k))
        total+=pmf
    return total

#Discrete distribution expansion
#This function converts discrete values and their counts into an expanded vector representation 
#and compares the observed and expected distributions using a two-sided K.S. test.
def ks_discrete_test(values, observed_counts, expected_counts):
  observed_distribution=[]
  expected_distribution=[]
  for value, observed, expected in zip(values, observed_counts, np.round(expected_counts)):
    observed_distribution.extend([int(value)]*int(observed))
    expected_distribution.extend([int(value)]*int(expected))
  return ks_2samp(observed_distribution, expected_distribution, alternative='two-sided')
